// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/login": {
            "post": {
                "description": "Authenticate user with provided credentials and generate JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User login information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Incorrect username or password",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "description": "Register a new user with the provided information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User registration successful",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "409": {
                        "description": "Conflict - Username or phone number already exists",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/user/signup/otpverification": {
            "post": {
                "description": "Otp verification with email id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Otp verfication of a new user",
                "parameters": [
                    {
                        "description": "User registration information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usercontrollers.OtpVerifiaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User registration successful",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "409": {
                        "description": "Conflict - Username or phone number already exists",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Login": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4
                },
                "id": {
                    "type": "integer"
                },
                "isblocked": {
                    "type": "boolean"
                },
                "lastname": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4
                },
                "otp": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 10
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4
                },
                "validate": {
                    "type": "boolean"
                }
            }
        },
        "usercontrollers.OtpVerifiaction": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "otp": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GigaHive",
	Description:      "Freelance application API in go using Gin frame work",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
